Improve value formatting
openspending/os-viewer pull request #142
Opened 2016-11-15 14:25 UTC by kravets-levko

1. Format values for all visualizations in the same manner, using suffixes ("thousands", "millions", etc.).
2. Make that suffixes locale-aware: use translation key `Value Formatting Scale` with following format:
`"suffix 1": scale1, "suffix 2": scale2`. Example: `"Billions": 1000000000, "Millions": 1000000, "Thousands": 1000` (order does not matter).

All features will work only with latest version of `babbage.ui` and `bubbletree` libraries.

2016-11-24 06:25 UTC, akariv requested changes

2016-11-24 06:25 UTC, akariv commented on app/config/translations.json
> -{
Let's make sure the file is formatted with indentation and sorted keys, so that changes are tracked more easily.

2016-11-24 06:25 UTC, akariv commented on app/front/scripts/config/config.js
> +        scale = '"Billions":1000000000,"Millions":1000000,"Thousands":1000';
Let's move the defaults to the `visualizations.formatValue`, in case there's a parsing problem.

2016-11-24 06:25 UTC, akariv commented on app/front/scripts/services/visualizations/index.js
> +      scale = {};
If we fail to parse, let's print something to the console.
Also, let's have the defaults set here and not above.

2016-11-25 08:50 UTC, kravets-levko commented
@akariv Code updated. I also fixed `download_translations.py` - I see that somebody added 'de' translation directly into 'translations.json', so I added some code to keep such translation string, and only update 'en' and 'es' from Google Spreadsheets

2016-11-25 10:42 UTC, akariv approved these changes

2016-11-25 10:42 UTC, merged